services:
  minio:
    image: minio/minio:RELEASE.2024-05-27T19-17-46Z
    command: server /data --console-address ":9001"
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_SITE_REGION: eu-west-3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo sleep 10;
      sleep 10;
      /usr/bin/mc config host add myminio http://minio:9000 admin adminadmin;
      /usr/bin/mc mb myminio/test-bucket;
      exit 0;
      "

  iceberg_rest:
    image: tabulario/iceberg-rest
    depends_on:
      iceberg_rest-db:
        condition: service_healthy
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=adminadmin
      - AWS_REGION=eu-west-3
      - CATALOG_WAREHOUSE=s3://test-bucket/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH__STYLE__ACCESS=true
      - CATALOG_CATALOG__IMPL=org.apache.iceberg.jdbc.JdbcCatalog
      - CATALOG_URI=jdbc:postgresql://iceberg_rest-db:5432/iceberg_restdb
      - CATALOG_JDBC_USER=iceberg_rest
      - CATALOG_JDBC_PASSWORD=password

  iceberg_rest-db:
    image: postgres:15.2
    init: true
    environment:
      POSTGRES_DB: iceberg_restdb
      POSTGRES_USER: iceberg_rest
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "iceberg_rest", "-d", "iceberg_restdb" ]
      interval: 5s
      retries: 5
